name: format

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pint:
    if: "!contains(github.event.head_commit.message, '[skip-format]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          tools: composer:v2
      - run: composer update --prefer-dist --no-interaction --no-progress
      - run: vendor/bin/pint
      - name: Commit formatting
        run: |
          if git diff --quiet; then exit 0; fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply Pint formatting [skip-format]"
          git push origin HEAD:main
